### ISSUE TITLE
Get/check available and installed plugin

### ISSUE THREAD

**Issue by back2arie** [Vheissu/CI-Plugin-System#2]
Hi

I'm proposing new function to get/check available and installed plugin, because sometimes we need it to do external check.

<pre>
function get_available_plugin()
{
    return Plugins::$plugins_pool;
}

function get_installed_plugin()
{
    return Plugins::$plugins_active;
}

function check_available_plugin($name)
{
    $available_plugin = Plugins::$plugins_pool;
    return array_key_exists($name, $available_plugin);
}

function check_installed_plugin($name)
{
    $installed_plugin = Plugins::$plugins_active;
    return array_key_exists($name, $installed_plugin);
}
</pre>

Please consider to add this to your plugin library.

**Comment by Vheissu** [comment]
Hi mate,

Thanks for the code! I'll test this out and let you know once I've added it in.
