### ISSUE TITLE
Error load

### ISSUE THREAD

**Issue by jonilgz** [Vheissu/CI-Plugin-System#3]
Fatal error: Call to a member function database() on a non-object in /XXXXX/Plugins.php on line 62.

**Comment by Vheissu** [comment]
I'm looking into this now. Hoping to have a pull request up in a day or two if I find an issue to fix :)

**Comment by Vheissu** [comment]
Give this commit a shot and let me know how you go mate. https://github.com/Vheissu/CI-Plugin-System/commit/9993ce5cf11b0d0e663d43f5aa54e97c2062e28a

**Comment by Vheissu** [comment]
Thanks for your pull request. Issue resolved.
